### PR TITLE
Improved dotfiles

### PR DESCRIPTION
**Pull request by pedsm**
1. Added an installation script in order to automatically install dependencies on Arch
2. Removed deprecated folder. Git has history
3. Added a cat alias to use bat instead. Bat is auto installed with the install script

### CODE REVIEW

**Comment by pedsm** [comment]
Bump

**Comment by jonathanballs** [comment]
Lol

**Comment by jonathanballs** [comment]
Not sure I think that install.sh is the right approach here. I'm not sure what is the right approach but I imagine there is some kind of tool to manage this cleanly.

**Comment by pedsm** [comment]
Bump

**Review by jonathanballs — CHANGES_REQUESTED** [review]
Please remove the alias of `cat` to `bat`. It's bad practice to overwrite system commands in this manner and provides no typing efficiency improvements as the commands are the same length.

**Comment by jonathanballs** [comment]
Thank you for this pull request - I really appreciate the time you have put into this however after thorough deliberation, I have unfortunately come to the conclusion that it is necessary to close this issue at this time.

I would like to explain the reasoning behind this decision in detail. I adhere to a very stringent policy concerning the management of open issues. Specifically, I have established a firm limit of five and a half years, beyond which issues cannot remain open. Unfortunately, the pull request under consideration has now exceeded this established timeframe. It is with regret that I must adhere to this policy and proceed with closing the issue.

In addition to the aforementioned policy, I would like to inform you of a significant change in my workflow. I have recently transitioned to using the software `chezmoi` for the management of my dotfiles. This new tool has proven to be highly effective and efficient for my needs. Consequently, the installation script that was the subject of this issue is no longer required within my current setup.

I want to express my deepest gratitude for your efforts and contributions. Your understanding and cooperation in this matter are greatly appreciated. Should you have any further questions or require additional information, please do not hesitate to reach out. I am more than willing to provide any further clarification or assistance you may need.

Thank you very much for your attention to this matter and for your continued support.

**Pull request closed without merging**
